/**
 * Central gameplay tuning values for Helios Drift.
 *
 * Edit values here, then rebuild/restart the app to apply them. Descriptions,
 * UI copy, and purely visual animation/layout values remain with their UI code.
 * Units: px, px/s, seconds, radians, credits, HP, or damage unless stated.
 */
export const GAME_CONFIG = {
  // Service code for the developer panel. Access expires on close or reload.
  developer: { accessCode: "dev" },

  colors: {
    amber: "#ffb03a",
    amberHot: "#ffe0a3",
    ice: "#6fe7ff",
    magenta: "#ff3d6e",
    orange: "#ff7a2a",
    rocks: {
      none: "#8d6a3d",
      homing: "#ff6f9a",
      bounce: "#6fe7ff",
      boom: "#ff7a2a",
      fast: "#f4f7ff",
      meteor: "#ffd27a",
      meteorite: "#ffc36b",
    },
  },

  themes: [
    { numeral: "I", name: "DEEP VOID", tint: "rgba(26,29,43,0.10)", stars: ["#ffe0a3", "#8d93ad"] },
    {
      numeral: "II",
      name: "VERDANT DRIFT",
      tint: "rgba(20,48,34,0.13)",
      stars: ["#c9ffd9", "#79a98c"],
    },
    {
      numeral: "III",
      name: "FROZEN BELT",
      tint: "rgba(18,42,60,0.15)",
      stars: ["#d9f4ff", "#7ba0bd"],
    },
    {
      numeral: "IV",
      name: "VIOLET STORM",
      tint: "rgba(44,24,58,0.15)",
      stars: ["#f0d4ff", "#a07bcd"],
    },
    {
      numeral: "V",
      name: "EMBER FIELD",
      tint: "rgba(58,25,18,0.15)",
      stars: ["#ffc9b0", "#c08268"],
    },
    { numeral: "VI", name: "THE CORE", tint: "rgba(70,32,8,0.18)", stars: ["#ffffff", "#ffd9a0"] },
    {
      numeral: "VII",
      name: "SOLAR CATACLYSM",
      tint: "rgba(80,38,6,0.26)",
      stars: ["#ffea88", "#ff9933"],
    },
  ],

  player: {
    hull: 100,
    armor: 0,
    thrust: 460,
    maxSpeed: 540,
    turn: 4.4,
    fireRateMul: 1,
    damageMul: 1,
    bulletSpeed: 720,
    crit: 0.06,
    critMult: 2.2,
    inaccuracy: 0.045,
    missiles: 3,
    maxMissiles: 3,
    missileRegen: 6.5,
    blastDamage: 68,
    blastRadius: 96,
    magnet: 150,
    creditChance: 0.72,
    creditChancePerRockSize: 0.07,
    creditValue: 1,
    leech: 0,
    collisionInvulnerability: 0.75,
    shipRadius: 14,
    movementDragPerFrame: 0.986,
    maxHullUpgrade: { perStack: 18, maxStacks: 3 },
  },

  weaponProgression: {
    maxLevel: 6,
    priceMultiplier: 1.55,
    priceRounding: 5,
    rarityBasePrices: { common: 120, rare: 280, epic: 560 },
    weapons: {
      pulse: {
        rarity: "common",
        weight: 1,
        name: "Pulse Cannon",
        short: "PULSE",
        baseDamage: 16,
        damagePerLevel: 0.12,
        baseRate: 4.6,
        ratePerLevel: 0.07,
        baseShots: 1,
        shotsEveryLevels: 2,
        speed: 720,
        life: 1.15,
        radius: 3.6,
      },
      spread: {
        rarity: "rare",
        weight: 0.7,
        name: "Scattershot Array",
        short: "SCATTER",
        baseDamage: 12.8,
        damagePerLevel: 0.12,
        baseRate: 3.55,
        ratePerLevel: 0.035,
        baseShots: 3,
        shotsPerLevel: 0.7,
        arc: 0.13,
        speed: 720,
        life: 1.15,
        radius: 3.6,
      },
      seeker: {
        rarity: "rare",
        weight: 0.7,
        name: "Seeker Pulse",
        short: "SEEKER",
        baseDamage: 7.4,
        damagePerLevel: 0.15,
        baseRate: 6.6,
        ratePerLevel: 0.065,
        baseShots: 1,
        shotsEveryLevels: 3,
        speed: 520,
        life: 2.2,
        radius: 3,
        arc: 0.2,
        turn: 7.5,
      },
      ricochet: {
        rarity: "rare",
        weight: 0.7,
        name: "Ricochet Blaster",
        short: "RICOCHET",
        baseDamage: 21,
        damagePerLevel: 0.15,
        baseRate: 3.05,
        ratePerLevel: 0.04,
        baseShots: 1,
        shotsEveryLevels: 4,
        baseBounces: 1,
        bouncesEveryLevels: 2,
        speed: 640,
        life: 2.6,
        radius: 4.5,
      },
      flak: {
        rarity: "rare",
        weight: 0.6,
        name: "Flak Cannon",
        short: "FLAK",
        baseDamage: 10.2,
        baseRate: 1.48,
        ratePerLevel: 0.05,
        baseShots: 1,
        shotsEveryLevels: 3,
        fuse: 0.45,
        speed: 560,
        life: 1.5,
        radius: 6,
        baseShrapnel: 7,
        shrapnelPerLevel: 2,
        shrapnelDamage: 9.5,
        shrapnelDamagePerLevel: 0.13,
      },
      arc: {
        rarity: "epic",
        weight: 0.4,
        name: "Arc Coil",
        short: "ARC",
        baseDamage: 10.8,
        damagePerLevel: 0.21,
        baseRate: 6,
        ratePerLevel: 0.07,
        speed: 620,
        life: 0.9,
        radius: 3,
        baseRange: 250,
        rangePerLevel: 18,
        baseChains: 2,
        chainsEveryLevels: 2,
        chainJumpRange: 200,
      },
      laser: {
        rarity: "epic",
        weight: 0.4,
        name: "Beam Emitter",
        short: "BEAM",
        baseDps: 140,
        dpsPerLevel: 0.28,
        baseRate: 5.2,
        ratePerLevel: 0.06,
        damage: 13,
        damagePerLevel: 0.2,
        speed: 1020,
        life: 1.2,
        radius: 3.2,
        range: 1100,
        heatRate: 0.36,
        heatReductionPerLevel: 0.06,
      },
      rail: {
        rarity: "epic",
        weight: 0.4,
        name: "Railgun",
        short: "RAIL",
        baseDamage: 19,
        damageScale: 2.6,
        damagePerLevel: 0.22,
        maxLevelDamageBonus: 1.18,
        baseRate: 4.6 * 0.42,
        ratePerLevel: 0.05,
        basePierce: 3,
        pierceEveryLevels: 2,
        speed: 960,
        life: 2.2,
        radius: 6,
        turn: 1.15,
        effectiveRange: 2112,
      },
    },
  },

  statUpgrades: {
    overclock: { max: 3, rarity: "common", weight: 1, fireRateMultiplier: 1.09 },
    hollow: { max: 3, rarity: "common", weight: 1, damageMultiplier: 1.12 },
    thruster: {
      max: 3,
      rarity: "common",
      weight: 1,
      thrustMultiplier: 1.09,
      speedMultiplier: 1.06,
      turnMultiplier: 1.04,
    },
    hull: { max: 3, rarity: "common", weight: 1, hullPerStack: 18 },
    armor: {
      max: 3,
      rarity: "rare",
      weight: 0.7,
      damageReductionPerStack: 0.12,
      maxDamageReduction: 0.36,
    },
    twin: { max: 1, rarity: "rare", weight: 0.7, extraShotsPerStack: 1 },
    pierce: { max: 4, rarity: "rare", weight: 0.7, extraPiercePerStack: 1 },
    crit: { max: 3, rarity: "rare", weight: 0.7, critPerStack: 0.2, critMultiplierPerStack: 0.1 },
  },

  salvageUpgradePrices: {
    twinCannons: { base: 90, max: 3 },
    overcharge: { base: 105, max: 3 },
    piercing: { base: 120, max: 2 },
    armor: { base: 75, max: 3 },
    shield: { base: 110, max: 3 },
    repairPulse: { base: 90, max: 3 },
    magnet: { base: 65, max: 3 },
    scan: { base: 70, max: 3 },
    speed: { base: 75, max: 3 },
  },

  asteroids: {
    sizes: {
      large: { size: 3, hp: 82, radius: 58 },
      medium: { size: 2, hp: 42, radius: 33 },
      small: { size: 1, hp: 20, radius: 18 },
    },
    radiusRandomMin: 0.86,
    radiusRandomMax: 1.16,
    hpPerScaledWave: 0.13,
    specialHpMultiplier: 1.15,
    scaledWaveMultiplier: 2,
    collision: {
      largeBase: 14,
      mediumBase: 9,
      smallBase: 5,
      damagePerRelativeSpeedPerSize: 0.03,
      minDamage: 5,
      maxDamage: 42,
      meteorBaseDamage: 18,
      meteorDamagePerRelativeSpeed: 0.02,
      meteorMinDamage: 18,
      meteorMaxDamage: 34,
      meteoriteDamage: 4,
      shipRamDamage: 22,
      meteoriteRamDamage: 999,
      shipRadius: 14,
      hitRadiusMultiplier: 0.86,
      invulnerability: 0.75,
    },
    traits: {
      homing: {
        unlockWave: 6,
        turnRates: { small: 1.3, medium: 1.8, large: 2.4 },
        smallSpeed: 117,
      },
      bounce: {
        unlockWave: 11,
        speeds: { small: 185, medium: 150, large: 120 },
        maxSpeedMultiplier: 1.3,
      },
      boom: {
        unlockWave: 16,
        maxAlive: 6,
        shakePerSize: 0.6,
        speeds: { small: 36, medium: 30, large: 24 },
        fuse: 0.35,
        triggerPad: 90,
        triggerRadiusFraction: 0.8,
        homeRange: 260,
        homeTurn: 0.95,
        blastRadiusMultiplier: 1.7,
        blastRadii: { large: 178, medium: 108, small: 66 },
        playerDamage: { large: 32, medium: 16, small: 8 },
        rockDamage: { large: 42, medium: 22, small: 11 },
      },
      fast: {
        unlockWave: 21,
        speeds: { small: 260, medium: 292, large: 320 },
        hpMultiplier: 1.8,
        damageMultiplier: 1.15,
        knockbackMultiplier: 1.3,
      },
      meteor: {
        speedMin: 520,
        speedMax: 700,
        radiusMultiplier: 1.35,
        hpBase: 120,
        hpPerScaledWave: 4,
        shardCountMin: 3,
        shardCountMax: 6,
      },
      meteorite: {
        xSpeed: 70,
        ySpeedMin: 45,
        ySpeedMax: 90,
        radiusMultiplier: 0.8,
        hpBase: 6,
        hpPerScaledWave: 0.4,
        playerDamage: 4,
        creditMin: 10,
        creditMax: 20,
      },
    },
    genericExplosionPlayerDamage: 6,
    bossFieldCap: 10,
    bossRockLifetime: 30,
  },

  enemies: {
    spikers: {
      unlockWave: 11,
      eightShotWave: 20,
      latePairFromWave: 20,
      latePairToWave: 25,
      secondSpawnChance: 0.25,
      hpBase: 215,
      hpPerWave: 44,
      radius: 31,
      speedMin: 105,
      speedMax: 145,
      turnIntervalMin: 2.2,
      turnIntervalMax: 4.2,
      turnAngle: 0.65,
      spinRate: 0.24,
      fireInterval: 4 / 1.2,
      lateFireInterval: 3.2 / 1.2,
      fireWarning: 0.65,
      boltSpeed: 225 * 1.5,
      boltDamage: 7,
      boltRadius: 5,
      boltLifetime: 4.2,
      playerContactDamage: 14,
    },
    sentinels: {
      hpBase: 55,
      hpPerWave: 22,
      radius: 21,
      boltDamage: 7,
      boltSpeed: 250,
      boltRadius: 5,
      boltLifetime: 4.2,
      boltRange: 720,
      fireIntervalMin: 3,
      fireIntervalMax: 4.4,
      lateFireIntervalReduction: 1.1,
      burstFromWave: 8,
      burstGap: 0.22,
      preferredDistance: 470,
      retreatDistanceAtLowHealth: 620,
      speed: 200,
      lowHealthSpeed: 235,
      playerContactDamage: 14,
      contactDamageToEnemy: 30,
      waveCaps: [2, 3, 4, 5, 6],
      countWaveThresholds: [1, 3, 5],
      countPerBand: [0, 1, 2, 3],
    },
    wardens: {
      ordinaryHpBase: 215,
      ordinaryHpPerWave: 44,
      escortHpBase: 210,
      escortHpPerWave: 56,
      radius: 30,
      boltDamage: 12,
      boltSpeed: 860,
      boltRadius: 13,
      boltLifetime: 2.2,
      rangeMin: 320,
      rangeMax: 1350,
      aimWarning: 0.6,
      aimOffset: 24,
      shotDelayMin: 2.4,
      shotDelayMax: 3.6,
      preferredDistance: 900,
      retreatDistanceAtLowHealth: 760,
      speed: 165,
      lowHealthSpeed: 200,
      turretLifetime: 10.5,
      turretHp: 2,
      turretIntervalMin: 6,
      turretIntervalMax: 11,
      turretCap: 3,
      playerContactDamage: 14,
      contactDamageToEnemy: 30,
    },
  },

  bosses: {
    finalWave: 25,
    waveBaseHp: 1800,
    hpPerScaledWave: 140,
    mk3Hp: 14000,
    mk4Hp: 22000,
    finalHp: 28000,
    bonusHp: 37000,
    earlyHpCeiling: 13000,
    contactDamage: 24,
    attackPhaseThresholds: [0.66, 0.33],
    regenesisShieldFraction: 0.1,
    regenesisShieldDuration: 30,
    baseRadius: 104,
    finalRadius: 135,
    bonusRadius: 151,
    baseAttackTimer: 2.6,
    finalAttackTimer: 1.9,
    attackTimerPerPhase: 0.55,
    abilityRockChance: 0.3,
    anomaly: { damage: 1, damageInterval: 1, damageRadiusFraction: 0.5 },
    mk4: { strikeDamage: 16, strikeRadius: 125, strikeWarning: 1.35 },
    mk6: {
      phaseLockFraction: 0.5,
      strikeCount: 5,
      strikeFirstWarning: 2.4,
      strikeWarningStep: 0.5,
      strikeRadiusMin: 150,
      strikeRadiusMax: 215,
      strikeExplosionDamage: 74,
      strikePlayerDamage: 30,
      beamArms: 4,
      enragedBeamArms: 8,
      beamSweepRate: 0.24,
      beamPlayerDamage: 9,
      beamDamageCooldown: 0.6,
      regenesisDamage: 28,
      regenesisRadius: 390,
      singularityPull: 420,
      singularityDuration: 7.5,
    },
    profiles: {
      1: {
        hpMultiplier: 1.2,
        timerMultiplier: 1,
        spawnWeight: 0.7,
        driftX: 0,
        projectileMultiplier: 1,
        rocksPerSpawn: 1,
      },
      2: {
        hpMultiplier: 1.495,
        timerMultiplier: 0.92,
        spawnWeight: 0.7,
        driftX: 6,
        projectileMultiplier: 1.1,
        rocksPerSpawn: 1,
      },
      3: {
        hpMultiplier: 1.89,
        timerMultiplier: 1.05,
        spawnWeight: 0.9,
        driftX: 10,
        projectileMultiplier: 1.05,
        rocksPerSpawn: 2,
      },
      4: {
        hpMultiplier: 2.4,
        timerMultiplier: 0.7,
        spawnWeight: 0.7,
        driftX: -4,
        projectileMultiplier: 1.1,
        rocksPerSpawn: 2,
      },
      5: {
        hpMultiplier: 1,
        timerMultiplier: 1.15,
        spawnWeight: 0.55,
        driftX: 0,
        projectileMultiplier: 1.35,
        rocksPerSpawn: 2,
      },
      6: {
        hpMultiplier: 1,
        timerMultiplier: 1,
        spawnWeight: 0,
        driftX: 0,
        projectileMultiplier: 1,
        rocksPerSpawn: 0,
      },
    },
  },

  waves: {
    wavesPerBoss: 5,
    scaledWaveMultiplier: 2,
    showerAfterWave: 10,
    showerDuration: 7.5,
    showerSpawnMin: 0.28,
    showerSpawnMax: 0.5,
    showerMeteoriteChance: 0.55,
    showerCompletionBonus: 100,
    showerCooldownWaves: 1,
    regularRockBaseCount: 3,
    regularRockCountScale: 0.85,
    regularRockCountCap: 9,
    wardenRockCountMultiplier: 0.55,
    waveCreditsBase: 80,
    waveCreditsPerWave: 24,
    meteorCollisionDamage: 14,
    bossEntryRockCount: 1,
    bossFieldRockCap: 10,
    bossEscortHpPerWave: 11,
    wardenEscortHpBase: 210,
    wardenEscortHpPerWave: 28,
    lateWardenHpBase: 215,
    lateWardenHpPerWave: 22,
    minimumRockCountWithWarden: 3,
    shipSpawnRockClearance: 280,
    bossAttackTimer: 2.2,
    bossMk3Speed: 110,
    bossMk6Speed: 38,
    bossBaseSpeed: 30,
  },

  salvage: {
    basePrice: 260,
    startingHp: 24,
    armorHpPerLevel: 12,
    armorDamageReductionPerLevel: 0.15,
    maxArmorDamageReduction: 0.6,
    rebuildTime: 2.5,
    assemblyTime: 1.8,
    startingPulseTimer: 4,
    upgradePriceMultiplier: 1.45,
    finalUpgradePriceMultiplier: 2.5,
    repairPulseHeal: 1,
    repairPulseLevel3Heal: 2,
    repairPulseIntervals: [1, 0.75, 0.5],
    repairQuietSeconds: 5,
    repairPulseRange: 150,
    repairPulseRangePerScan: 50,
    shieldShares: [0.2, 0.35, 0.5],
    playerFeederRatePerLevel: 0.05,
    droneFeederRatePerLevel: 0.1,
    magnetRangeBase: 76,
    magnetRangePerLevel: 90,
    magnetRangePerScan: 60,
    magnetLevel3RangeBonus: 90,
    targetRangeBase: 310,
    targetRangePerScan: 150,
    scanLevel3TargetBonus: 150,
    attachedWeaponRangeBonus: 120,
    baseShotDamage: 3.5,
    weaponDamageScale: 0.22,
    overchargeDamagePerLevel: 1.8,
    overchargeMultiplierPerLevel: 0.28,
    overchargeReductionPerLevelAfterFirst: 0.08,
    overchargeLevel3Surge: 1.65,
    baseShotSpeed: 430,
    weaponShotSpeedScale: 0.78,
    scanShotSpeedPerLevel: 22,
    beamDamageScale: 0.18,
    arcDamageScale: 0.45,
    starterFireInterval: 1.65,
    attachedFireInterval: 1.45,
    overchargeFireReduction: 0.18,
    twinCadenceReduction: 0.14,
    minFireInterval: 0.4,
    twinStarterShotsPerLevel: 1,
    maxMultipleShots: 4,
    bodyScalePerUpgrade: 0.035,
    bodyScaleCap: 0.34,
    rockCollisionMeteorDamage: 14,
    rockCollisionMeteoriteDamage: 4,
    rockCollisionBaseDamage: 8,
    rockCollisionPerSize: 4,
  },

  progression: {
    startingXpNext: 100,
    nextLevelXpBase: 100,
    nextLevelXpExponent: 1.26,
    xpPerScaledWave: 0.024,
    sentinelXp: 60,
    wardenXp: 120,
    rockXp: { large: 32, medium: 18, small: 11, traitMultiplier: 1.3, meteor: 22, meteorite: 8 },
    levelUpHullHeal: 20,
    levelUpRerollStartingCost: 30,
    levelUpRerollCostMultiplier: 1.8,
  },

  pickups: {
    pickupDistance: 26,
    lifetime: 20,
    repairChance: 0.12,
    rockDropCount: { large: 3, medium: 2, small: 1 },
    rockCreditValue: { large: 12, medium: 7, small: 4 },
    playerCreditScoreMultiplier: 6,
    dronePickupRadius: 22,
    droneCreditScoreMultiplier: 4,
    sentinelCreditCount: 3,
    sentinelCreditValue: 14,
    wardenCreditCount: 4,
    wardenCreditValue: 20,
    bossDropCount: 8,
    bossDropValue: 36,
    finalBossDropCount: 12,
    finalBossDropValue: 60,
  },

  simulation: {
    maxScreenShake: 12,
    shakeDecayPerSecond: 0.0001,
    frameDeltaCap: 0.05,
    arcTick: 0.12,
    pickupDragPerFrame: 0.985,
    pickupPullMin: 120,
    pickupPullMax: 900,
    starCount: 260,
    levelUpRerollCostMultiplier: 1.8,
    particleCap: 700,
    explosionTimeScale: 0.62,
    playerAssistRange: 920,
    playerAssistAngleCap: 0.085,
    missileTargetRange: 900,
    missileSpeed: 380,
    guidedMissileRange: 900,
    guidedRailRange: 1500,
    guidedOtherRange: 520,
    enemyBulletRadius: 5,
    enemyBulletLifetime: 5,
    bossRingDamage: 8,
    bossFanDamage: 9,
    bossShockwaveRadiusBase: 190,
    bossShockwaveRadiusPerMk: 35,
    bossShockwaveLowHealthGrowth: 0.75,
    bossShockwavePlayerDamage: 22,
    bossStrikePlayerDamage: 24,
    bossStrikePlayerRadius: 150,
    bossStrikeExplosionDamage: 62,
    bossRingProjectileSpeed: 165,
    bossFinalRingProjectileSpeed: 190,
    bossProjectileSpeedPerPhase: 15,
    bossFanProjectileSpeed: 240,
    bossFinalFanProjectileSpeed: 280,
    bossFinalDamageMultiplier: 1.4,
    bossProjectileBaseCount: 14,
    bossProjectileCountPerPhase: 4,
    bossFinalProjectileCountBonus: 4,
    bossProjectileMinRingCount: 10,
    bossFanBaseCount: 3,
    bossFanCountPerPhase: 1,
    bossFinalFanCountBonus: 1,
    bossFinalStrikeDamageMultiplier: 1,
    bossFinalWaves: 25,
  },
} as const;
